### ISSUE TITLE
What is your plan for mohi? 

### ISSUE THREAD

**Issue by olizilla** [mohi-io/mohi-io-www#1]
Reuse is good, but the public website for mohi is currently a clone of http://david-dm.org.
It's nice that you explicitly state that on the github repo, and the fork history is maintained, but there is no acknowledgement on the actual website. 

The main issue here is the reuse of the logo, text copy, and entire look and feel of the existing site which feels a bit rude as it was done without contacting the original authors, as far as I'm aware.

I personally am fan of maven and a recovering Java developer, so I'm pleased to see a similar idea rolling out for the Java ecosystem. @alanshaw and the contributors to david are up for collaborating; we love open-source, so please get in touch and let us know what your plans are.

**Comment by Zenedith** [comment]
Thanks you for your  feedback.
My first idea was to create pull request to david-dm project, adding support to java projects.
Second idea was to create separate service based on dawid-dm but not using dawid-dm reserved resources such as logo, texts and etc.
The last and final decision I made is to create a whole new service without any common parts - currently I'm working on new frontend (can be view on http://104.131.26.93/) and make a new backend for it (https://github.com/mohi-io/mohi-io-api) based on hackathon starter.

I'm sorry for temporary reused resources from david-dm on "old" mohi.io.

If you or someone else want to discus more about it, send my an email: zenedith@wp.pl
